version: '3'
services:
    db:
        image: 'postgres:latest'
        environment:
          POSTGRES_PASSWORD: senha123
          POSTGRES_USER: devTaskmanager
          POSTGRES_DB: taskmanager
        ports:
          -  "5432:5432"
        volumes:
          -  ./pgdata:/var/Lib/postgressqL/data      